# Generated by Django 3.2.6 on 2021-08-31 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0002_type_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_information',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppid.type_action'),
        ),
        migrations.AlterField(
            model_name='type_action',
            name='type_action',
            field=models.TextField(null=True),
        ),
    ]
