# Generated by Django 3.2.6 on 2021-08-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0003_auto_20210831_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_information',
            name='Information',
            field=models.TextField(null=True),
        ),
    ]
