# Generated by Django 3.2.6 on 2021-08-31 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0005_alter_form_information_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_information',
            name='dinas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppid.dinas'),
        ),
    ]
