# Generated by Django 3.2.6 on 2021-09-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0010_auto_20210903_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='download',
            field=models.ManyToManyField(related_name='post_download', to='ppid.IpModel'),
        ),
        migrations.AlterField(
            model_name='data',
            name='read',
            field=models.ManyToManyField(related_name='post_views', to='ppid.IpModel'),
        ),
    ]
