# Generated by Django 3.2.6 on 2021-09-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ppid', '0011_auto_20210903_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order_menu', models.IntegerField(default=0)),
                ('kind', models.IntegerField(blank=True, choices=[('0', 'Backend'), ('1', 'Frontend')], default='1')),
                ('is_visibled', models.BooleanField(default=True)),
                ('is_master_menu', models.BooleanField(default=False)),
                ('is_statis_menu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ppid.menu')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
    ]
