# Generated by Django 3.2.6 on 2021-09-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ppid', '0012_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='download',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_download', to='ppid.IpModel'),
        ),
        migrations.AlterField(
            model_name='data',
            name='read',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_views', to='ppid.IpModel'),
        ),
        migrations.CreateModel(
            name='sengketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telp', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('name_kuasa', models.CharField(blank=True, max_length=225, null=True)),
                ('address_kuasa', models.TextField(blank=True, null=True)),
                ('telp_kuasa', models.CharField(blank=True, max_length=225, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=225, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
    ]
