# Generated by Django 3.2.6 on 2021-09-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0013_auto_20210903_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sengketa',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
