# Generated by Django 3.2.6 on 2021-09-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0017_auto_20210906_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinas',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
