# Generated by Django 3.2.6 on 2021-09-06 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('ppid', '0018_alter_dinas_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinas',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='dinas',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
