# Generated by Django 3.2.6 on 2021-09-06 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppid', '0019_auto_20210906_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
