# Generated by Django 3.2.6 on 2021-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0021_auto_20210909_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='code',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
