# Generated by Django 3.2.6 on 2021-09-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid', '0023_auto_20210909_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='pelayanan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='permohonan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
